# Generated by Django 6.0.3 on 2026-03-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisconnectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_mac', models.CharField(max_length=17)),
                ('user_hostname', models.CharField(blank=True, max_length=100)),
                ('disconnected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-disconnected_at'],
            },
        ),
    ]
